version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  geth:
    image: ethereum/client-go
    ports:
      - '8545:8545'
    command: --rpc --rpcaddr 0.0.0.0 --testnet --fast --cache 512
  daemon:
    build: ./daemon/
    links:
      - redis
      - geth
    env_file:
      - .docker.env
